name: Build Containers
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 800
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push build.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/build.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/context-transfer-engine-build:latest

      - name: Build and push deploy.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/deploy.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/context-transfer-engine:latest

      - name: Build and push redis_bench.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/redis_bench.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/iowarp-redis-bench:latest

      - name: Build and push wrp_cte_bench.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/wrp_cte_bench.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/iowarp-cte-bench:latest
